<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2018-06-21 17:34:24
 * @@Modify Date: 2018-06-21 18:12:31
 * @@Function:
 */
?>
<div class="top-currency has-child">
	<a class="currency-selected" href="#"><?php  echo __('Dollar (US)', 'aloexpert'); ?></a>
	<ul class="sub-menu-top">
		<li><a href="#"><?php  echo __('Pound (GBP)', 'aloexpert'); ?></a></li>
		<li><a href="#"><?php  echo __('Euro (EUR)', 'aloexpert'); ?></a></li>
		<li><a href="#"><?php  echo __('Dollar (USD)', 'aloexpert'); ?></a></li>
	</ul>
</div>
