<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2018-06-21 17:34:24
 * @@Modify Date: 2018-06-21 18:16:30
 * @@Function:
 */
?>
<?php
	global $alothemes;
?>
<div class="top-language has-child">
	<a class="language-selected" href="#"><?php  echo __('Language: English', 'aloexpert'); ?></a>
	<ul class="sub-menu-top">
		<li><a href="#"><img src="<?php echo esc_url($alothemes->get_theme_url('images/Hungary.png')) ?>" alt="flag"><?php  echo __('Hungary', 'aloexpert'); ?></a></li>
		<li><a href="#"><img src="<?php echo esc_url($alothemes->get_theme_url('images/German.png')) ?>" alt="flag"><?php  echo __('German', 'aloexpert'); ?></a></li>
		<li><a href="#"><img src="<?php echo esc_url($alothemes->get_theme_url('images/French.png')) ?>" alt="flag"><?php  echo __('French', 'aloexpert'); ?></a></li>
		<li><a href="#"><img src="<?php echo esc_url($alothemes->get_theme_url('images/Canada.png')) ?>" alt="flag"><?php  echo __('Canada', 'aloexpert'); ?></a></li>
	</ul>
</div>
