<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2018-06-14 15:31:24
 * @@Function:
 */
// if(!is_front_page()) return;
$options 		 = magiccart_options();
if(!$options['popup-action']) return;
$widthPopup 	 = isset($options['popup-maxwidth']) ? $options['popup-maxwidth'] : 400;
$heightPopup 	 = isset($options['popup-maxheight']) ? $options['popup-maxheight'] : 300;
$popupBackground = isset($options['popup-background']['url']) ? $options['popup-background']['url'] : '';
$classer = $this->getData('el_class');
?>

<?php  if($options['popup-action'] && is_front_page()) ?>
<div class="newsletter-popup <?php echo esc_attr($classer)?>">
	<ul id="inline-popups" data-popup-cookie="<?php echo esc_attr($options['popup-cookie']) ?>" data-popup-delay="<?php echo esc_attr($options['popup-delay']) ?>">
		<li><a href="#newsletter-popup" data-effect="mfp-3d-unfold">3d unfold Popup</a></li>
	</ul>
	<div id="newsletter-popup" style=" <?php echo $widthPopup ? 'max-width:' . (int) $widthPopup : ''; ?>px;
							  <?php echo $heightPopup ? 'max-height:' . (int) $heightPopup . 'px' : ''; ?>;
							  background-image: url(<?php echo esc_attr($popupBackground); ?>);" class="newsletter-popup mfp-with-anim mfp-hide">
		<div class="block-content">
		<div class="content-inner">					  
		<?php if(isset($options['popup-content']) && $options['popup-content'] != "") { ?>
			<div class="popup-content">
				<?php print_r($options['popup-content']); ?>
			</div>
		<?php } ?>
		<div class="popup-newsleter">
	        <div class="tnp tnp-widget-minimal">
			    <form action="<?php echo esc_url( home_url( '/' ) ) . '?na=s';  ?>" method="post" id="newsletter-validate-detail-popup">

		            <span class="title"><?php echo __("Newsletter", 'aloexpert'); ?>: </span>
		            <div class="form-subscribe clearfix">
		            	<div class="block-subscribe">
		            		<div class="input-box">
			                <input type="hidden" name="nr" value="widget-minimal"/>
			                <input type="email" required name="ne" id="newsletter-sign-up" value="" title="<?php echo esc_attr__("Sign up for our newsletter", 'aloexpert'); ?>" placeholder="<?php echo esc_attr__("Enter your email address", 'aloexpert'); ?>" class="tnp-email">
				            </div>
				            <div class="action">
				            	<button type="submit" title="<?php echo esc_attr__("Subscribe", 'aloexpert'); ?>" class="tnp-submit"><span><?php echo __("Subscribe now!", 'aloexpert'); ?></span></button>
				            </div>
		            	</div>
	            	</div>
			    </form>
			</div>
	    </div>
	    </div>
	    </div>
	</div>
</div>
