<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2018-06-21 17:34:24
 * @@Modify Date: 2018-06-21 18:30:13
 * @@Function:
 */
?>
<div class="top-right">
	<ul>
		<li><a href="#"><?php echo __('Order Tracking', 'aloexpert') ?></a></li>
		<li><a href="<?php echo esc_url( site_url('checkout') ); ?>"><?php echo __('Checkout', 'aloexpert') ?></a></li>
		<li><a href="#"><?php echo __('Store Localtion', 'aloexpert') ?></a></li>
		<li><a href="<?php echo esc_url( site_url('about-us') ); ?>"><?php echo __('About', 'aloexpert') ?></a></li>
	</ul>
</div>
