<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-12 11:29:45
 * @@Modify Date: 2018-06-10 15:28:20
 * @@Function:
 */


$menu  = 'menu-vertical';
$_type = has_nav_menu($menu) ? 'theme_location' : 'menu';
?>
<div class="vmagicmenu clearfix">
    <div class="block-title block-title-vmagicmenu v-title">
        <strong>
            <span class="icon-menu">
                <span></span>
                <span></span>
                <span></span>
            </span>
            <span class="vmagicmenu-subtitle"><?php echo __('Categories', 'aloexpert'); ?></span>
        </strong>
    </div>
    <?php
        $allCategories = '<li class="all-cat" style="display:none;"><span>' . __('All Categories', 'aloexpert') . '</span><span style="display: none;">' .__('Close') . '</span></li>';
        wp_nav_menu(array(
            $_type    => $menu,
            'items_wrap'        => '<ul id="%1$s" class="%2$s nav-desktop sticker">%3$s' . $allCategories . '</ul>'
        ));
     ?>
</div>
