<?php 
	$options = $this->getOptions();
	$selector = 'alo-content-'.rand(0,999999999);
?>
<div class="box-brand">
    <div class="<?php echo esc_attr($selector) ?>">
        <div class="feature-brand"><h3 class="title"><?php echo __('Featured brand', 'aloexpert') ?></h3></div>
    	<div class="shopbrand" <?php foreach($options as $key => $value){?>
                                               data-<?php echo esc_attr($key); ?>='<?php echo esc_attr($value); ?>'
                                       <?php } ?> >
    				<?php
                        $attribute  = 'pa_' . SHOPBRAND;
                        $url_filter = site_url('shop') . '?filter_' . SHOPBRAND .'=';
                        foreach($this->_brands as  $brand){
							// $url = get_term_link('adidas', $attribute);
                            // if($url instanceof WP_Error) $url = '#';
                            $url = isset($brand['brand']) ? $url_filter . $brand['brand'] : '#';
                     		echo '<div class="item type-product"><div class="img-brand"><a href="'. esc_url($url) .'"><img src="' . esc_url($brand['img']) . '" alt="' . esc_attr($brand['name']) . '" /></a></div></div>';
                        }
                    ?>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	(function ($) {
		var shopbrand  = $('.<?php echo $selector ?> .shopbrand');
		if(shopbrand.length) $('head').append(magicproduct(shopbrand, '.item'));
    })(jQuery);
});
</script>
