<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2018-03-13 18:58:02
 * @@Function:
 */

$classer = $this->getData('el_class');
?>
<div id="footer-copyright" class="<?php echo esc_attr($classer) ?> footer-copyright">
        <div class="license copy-right">
            <address>
                Copyright &copy; 2018 <a class="active" href="<?php echo esc_url( home_url( '/' ) ); ?>">Expert</a> Woocommerce theme. All rights reserved
            </address>
        </div>
</div>

