<?php 
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2017-08-13 18:45:34
 * @@Modify Date: 2018-05-30 18:00:44
 * @@Function:
 */

$options  = $this->getOptions();
$selector = 'alo-content-'.rand(0,999999999);
$classer = $this->getData('el_class');
?>
<div class="box-blog <?php echo esc_attr($classer) ?>">
    <div class="<?php echo esc_attr($selector) ?>">
        <div class="blogtabs"><h3 class="title"><?php echo __('Lastest blog', 'aloexpert'); ?></h3></div>
        <div class="magicpost <?php echo $this->getData('slide') ? 'slider' : 'grid'?>" <?php foreach($options as $key => $value){?>
                                               data-<?php echo esc_attr($key); ?>='<?php echo esc_attr($value); ?>'
                                       <?php } ?> >
    		<?php 
                foreach($this->_posts as  $post){
                    $image = get_the_post_thumbnail($post);
                    $url   = get_permalink( $post );
            ?>
                    <div class='item'>
                        <?php if($image){ ?>
                            <div class="post-thumb"><a href="<?php echo esc_url($url) ?>"><?php echo $image ?></a></div>
                        <?php } ?>
                        <div class="post-desc">
                            <span class="meta-date">
                                    <i class="fa fa-calendar"></i>
                                    <a href="<?php echo esc_url( get_the_permalink($post) ); ?>">
                                            <?php echo get_the_date( "M d Y", $post->ID )?>
                                                
                                    </a>
                            </span>
                            <h3 class="title-post"><a href="<?php echo esc_url( $url ) ?>"><?php echo $post->post_title ?></a></h3>
                            <?php 
                            if( has_excerpt( $post->ID ) ){
                                echo '<div class="post-excerpt">' . get_the_excerpt($post) . '</div>';
                            }else{
                                echo '<div class="post-desc">' . get_the_content($post) . '</div>';
                            }
                            ?>
                            <div class="post-info post-meta">
                                <span class='meta-author'>
                                    <i class="fa fa-user"></i>
                                    <?php echo __('By:', 'aloexpert'); ?>
                                    <a href="<?php echo esc_url( get_author_posts_url( $post->post_author ) ); ?>"><?php echo get_the_author_meta("user_nicename", $post->post_author) ?>
                                        
                                    </a>
                                </span>
                                <span class='meta-comments'>
                                    <i class="fa fa-comments"></i>
                                    <a href="<?php echo esc_url( get_comments_link( $post->ID ) ); ?>"><?php echo $post->comment_count; ?> <?php echo __('Comment(s) ', 'aloexpert'); ?>
                                        
                                    </a>
                                </span>
                            </div>
                            <div class="post-action"><a class="read-more" href="<?php the_permalink();?>"><?php esc_html_e( 'Read more', 'aloexpert' );?></a></div>
                        </div>
                    </div>
            <?php
                }
            ?>
        </div>
    </div>
</div>
<script type="text/javascript">
jQuery(document).ready(function(){
	(function ($) {
		var magicpost  = $('.<?php echo $selector ?> .magicpost');
		if(magicpost.length) $('head').append(magicproduct(magicpost, '.item'));
    })(jQuery);
});
</script>





