<div class='wrap'>
    <h1><?php echo __('Magiccart Import', 'aloexpert') ?></h1>
    <?php echo $this->getData('message'); ?>
    <form method="post" action='' enctype="multipart/form-data">
         <table class="form-table">
            <tbody>
                <tr>
                    <th><label><?php echo __('Select theme', 'aloexpert') ?><span style="color:red;">*</span> : </label></th>
                    <td>
                        <select name="theme">
                            <?php
                                $themes = $this->getData('theme');
                                foreach ($themes as  $theme) {
                                    echo '<option value="'. esc_attr($theme['label']) .'"> '. $theme['value'] .' </option>';
                                }
                            ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th><label><?php echo __('Overwrite Posts or Pages if exist', 'aloexpert') ?><span style="color:red;">*</span> : </label></th>
                    <td>
                        <input name="overwrite" checked type="checkbox" value="1" />
                    </td>
                </tr>
<!--                 <tr>
                    <th><label><?php echo __('Activate', 'aloexpert') ?><span style="color:red;">*</span> : </label></th>
                    <td>
                        <input name="activate" type="checkbox" value="1" />
                    </td>
                </tr> -->
            </tbody>
       </table>
       <input type="submit" name="submit" id="mp-btn-change" class="button button-primary" value="<?php echo esc_attr__('Import', 'aloexpert') ?>">
    </form>
</div>
