<?php //$this->getStartFile(); ?>
<?php
    //$lazy = $this->get_options('lazy-load');
?>
<div class="mage-magictabs mc-<?php echo sanitize_html_class($key);?>">
    <div class="products products-grid">
        <?php 
            $options            = $this->getData();
            $args['cart']       = $options['cart'];
            $args['compare']    = $options['compare'];
            $args['wishlist']   = $options['wishlist'];
            $args['review']     = $options['review'];
            $args['sec']        = 0;
            if($collection->have_posts() ){
                echo '<ol class="products items" >';
                    while ( $collection->have_posts() ) : $collection->the_post();
                        $args['sec'] += 50;
                        wc_get_template( 'content-product-timer3.php', $args ); 
                    endwhile; 
                echo '</ol>';
            }else{
                echo '<p class="woocommerce-info">'. __('No products were found matching your selection.', 'aloexpert') .'</p>';
            }
        ?>
	</div>
</div>
<?php //$this->getEndFile(); ?>

